services:
  - type: web
    name: internconnect-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDirectory: Backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12